### ISSUE TITLE
Add a way to read current index

### ISSUE THREAD

**Issue by AJHenry** [osdnk/react-native-reanimated-bottom-sheet#21]
This project is great and shows a lot of promise, but currently, there is no way to read the current index of the sheet and wanted to propose a feature to read this state

Perhaps we can add a function prop `onIndexChange(prev, current)` that the user would pass in that would get called anytime the current index changes.

**Comment by osdnk** [comment]
Hello, 
I find it a little bit tricky because this change is not a discrete change. 
You know, it's quite difficult to asses when we actually change the index. IS it on start snapping? Or ending? Or when we start assuming that this interaction leads to the index's change?
I think you need to determine it on yourself using `callbackNode`. It has information about position and then you may get the information you want in a way you want. 😄

**Comment by Eyesonly88** [comment]
I'd be happy with just `onChange` event that fires when the bottom sheet moves from one snap point to the other.

**Comment by maxschmeling** [comment]
I get why this is difficult because there are in-between states, but I wonder if something like `onSnapLeave` and `onSnapComplete` would be appropriate... so when dragging away from a snap you get the leave event and when it settles at a snap point, you get the completion event...

I know that may still not be trivial but it's a thought.
